### ISSUE TITLE
SourcePath in AwesomeMarkerAsset when installing with Composer

### ISSUE THREAD

**Issue by sergeantjonas** [2amigos/yii2-leaflet-awesome-plugin#4]
SourcePath is wrong, it should be '@vendor/2amigos/yii2-leaflet-awesome-plugin/src/assets' I believe, instead it is '@vendor/2amigos/yii2-leaflet-awesome-plugin/assets' right now.

**Comment by tonydspaniard** [comment]
Thanks!

**Comment by Okeanos** [comment]
This fix is not available in any (stable) release and requires dev-master dependency settings. Could you fix that as well?
